### PR TITLE
fix(cli): Fix cli to work with COMMIT_EDITMSG, custom path or text

### PR DESCRIPTION
**Pull request by maxcnunes**
Sometime ago I had included support to validate a commit message from a text instead of only from files.
The validation from a commit message argument stopped working on adding support for GIT GUI tool: maxcnunes@d850cf4

This fixing makes CLI support 3 usage ways:
1. Default usage is not passing any argument. It will automatically read from COMMIT_EDITMSG file.
2. Passing a file path argument. For instance GIT GUI stores commit msg @GITGUI_EDITMSG file.
3. Passing commit message as argument. Useful for testing quickly a commit message from CLI.

### CODE REVIEW

**Comment by maxcnunes** [comment]
@kentcdodds or @spirosikmd could you please review this? Thanks!

**Comment by Garbee** [comment]
Kent is no longer maintaining the project.

Is this keeping the original CLI behavior? If not we need to revert the original commit causing the breakage and add a unit test to cover it. Then retry a fix on the original problem.

**Comment by maxcnunes** [comment]
@Garbee It is covering all possible behaviors for the CLI as I had described previously with the `3 usage ways`. I will add tests for the CLI so we don't end up having another regression as that commit did in this case.

**Comment by Garbee** [comment]
> It is covering all possible behaviors for the CLI

But is this in any way modifying the CLI from the way it worked *before*?

**Comment by maxcnunes** [comment]
No. Still have the same behaviors. Initially the cli only worked validating the commit message from `COMMIT_EDITMSG`. In March I added support to validate also from an argument ([my PR](https://github.com/conventional-changelog/validate-commit-msg/pull/71)). And few days ago were added support to validate from git gui as well ([commit](https://github.com/conventional-changelog/validate-commit-msg/commit/d850cf47265d5ff18e86a3a743678ecfc7d66c03)). But that last change end up removing the support I had added previously. 
This PR include back support for commit message as argument. Indepedently of which source is been used all them have the same validation behaviors.

**Comment by stevemao** [comment]
Is it fixing the same problem as https://github.com/conventional-changelog/validate-commit-msg/pull/87?

**Comment by maxcnunes** [comment]
Yes, It is. And is also covering a problem which I have commented in that
PR.

**Comment by maxcnunes** [comment]
@Garbee Any plans merging it to master? Or is there any reason for not accepting it?

**Comment by Garbee** [comment]
I just need to sit down and test it manually. Will do that tomorrow, was working on other issues that were filed earlier today when I went to work on the project.

**Comment by krishna63** [comment]
@maxcnunes : In my project, I am passing  `GITGUI_EDITMSG` as some developers commit thru `CLI` and others thru `GIT GUI`. To achieve this we have made changes and created a [PR](#79) and it was working fine in CLI and GIT GUI. 
Now, I have updated to latest version, but i am unable to commit thru `CLI`, when i am passing the `GITGUI_EDITMSG` as a parameter to `validate-commit-msg` . With this PR code changes it works only in `GIT GUI` but not in `CLI`. 

Scripts section of Package.json file
`
"scripts": {
"commitmsg": "validate-commit-msg GITGUI_EDITMSG",
}

`

cc: @Garbee , @kentcdodds

**Comment by maxcnunes** [comment]
@krishna63 The problem is that you are specifying in your script to always use the `GITGUI_EDITMSG` file. Independently if you are committing from CLI or GUI tool. Since that file is only generated by GUI commits that script won't work with CLI commits.
We could add a fallback if the specified file doesn't exists then use the default one `COMMIT_EDITMSG`. But that could be misleading since you are specifying a file and the validator would end up using another. In that case I would prefer add support passing arguments to the this cli such as:
```
--gui (which would read from `GITGUI_EDITMSG`)
--file (which would read from a path)
--message (which would read from the input text)
# these 3 above couldn't be used together
--enable-fallback (which would read from `COMMIT_EDITMSG` in case the other rules failed)
# and if no argument provided would read from `COMMIT_EDITMSG` by default
```
For me that is the best approach. Is much more explicit of what is going on.

@Garbee I can work implementing the fallback by default (first option) or adding support for arguments (second option). Just let me know what you prefer.

**Comment by cmalard** [comment]
Another approach : pass no argument and let the tool check if there is a `GITGUI_EDITMSG` or a `COMMIT_EDITMSG` :-)
This should cover both cases, allow us to remove the file option (it would become useless ?) and most important, the argument would be the same so everyone could work with the tool he wants without changing the config hook.

**Pull request merged**
